### ISSUE TITLE
migrate repo to fprime community

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fprime-workspace-image#33]
as suggested by @thomas-bc in https://github.com/capsulecorplab/fprime-workspace-image/issues/32

**Comment by capsulecorplab** [comment]
@thomas-bc what is the process for migrating a repo to the fprime-community? I'm currently in the process of [building documentation](https://github.com/capsulecorplab/fprime-workspace-image/pull/35) and testing fprime [v3.4.0](https://github.com/nasa/fprime/releases/tag/v3.4.0) and am thinking the migration should happen sooner rather than later as to ensure the CI builds will work on the fprime-community GitHub

**Comment by thomas-bc** [comment]
@capsulecorplab 
We don't have a formal process to transfer a repository. Since it [requires write permission to the organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), it's a little tricky. What we have done in the past is:

1) repo maintainer (you) transfers repo to an F´ maintainer
2) F´ maintainer transfers repo to F´ community
3) original repo maintainer is granted privileges to the repo in F´ community

Would you like to proceed this way? Feel free to transfer the repo over to me, I will transfer it to F´ community and grant you write/issue management permissions.

Another solution is for us to fork your repository in F´ community, and continue development from there. Whichever way you prefer!

**Comment by capsulecorplab** [comment]
> What we have done in the past is:
> 
> 1) repo maintainer (you) transfers repo to an F´ maintainer
> 2) F´ maintainer transfers repo to F´ community
> 3) original repo maintainer is granted privileges to the repo in F´ community
> 
> Would you like to proceed this way? Feel free to transfer the repo over to me, I will transfer it to F´ community and grant you write/issue management permissions.


@thomas-bc This approach sounds good! I'll go ahead and transfer the repo over to you

**Comment by thomas-bc** [comment]
https://github.com/fprime-community/fprime-workspace-image

There we go! You should have maintaining privileges. Also added an entry in the F´ Community README https://github.com/fprime-community

Wohoo 🎉

**Comment by thomas-bc** [comment]
Let me know if there's anything else you need

**Comment by capsulecorplab** [comment]
Awesome! Thanks @thomas-bc !
